export enum ProductOfferFlashType {
  Most_Popular = 'Most_Popular',
  Official_Stores = 'Official_Stores',
  Top_Deals = 'Top_Deals',
  Fashion = 'Fashion',
  Beauty_and_Personal_Care = 'Beauty_and_Personal_Care',
  International_Offers = 'International_Offers',
  Kids_Fashion = 'Kids_Fashion',
  Grocery_and_Pets = 'Grocery_and_Pets',
  Home_and_Kitchen = 'Home_and_Kitchen',
  Toys = 'Toys',
  Electronics = 'Electronics',
  Baby_Care = 'Baby_Care',
  Books_and_Stationery = 'Books_and_Stationery',
  Computers_and_Accessories = 'Computers_and_Accessories',
  Mobile_Phones_and_Devices = 'Mobile_Phones_and_Devices',
  Auto_and_Moto = 'Auto_and_Moto',
  Sports_and_Leisure = 'Sports_and_Leisure',
  More_Local_Deals = 'More_Local_Deals',
}
